# Pour nginx
# Fichier de configuration par défaut 

server {
    listen 86;
    server_name localhost;

    root /var/www/html;
    index index.php;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:8000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

# j'ecoute sur le port 86 et si je veux executer un site de php je vais sur le pour 8000 = php-fpm
# Pour le site web, je vais sur le port 86
